# Generated by Django 4.1.1 on 2022-10-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_rename_weigth_animal_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Macho", "Male"),
                    ("Femea", "Female"),
                    ("Não informado", "Other"),
                ],
                default="Não informado",
                max_length=15,
            ),
        ),
    ]
