# Generated by Django 4.1.1 on 2022-10-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_alter_animal_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
