# Generated by Django 4.1.1 on 2022-10-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0004_alter_animal_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
