# Generated by Django 4.1.1 on 2022-10-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0007_remove_animal_animal_animal_trait"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="trait",
            new_name="traits",
        ),
    ]
