# Generated by Django 4.1.1 on 2022-10-05 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("animals", "0008_rename_trait_animal_traits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="groups.group",
            ),
        ),
    ]
